/**
 * seed-real-profiles.ts
 * Wipes and re-seeds all pets + all services with accurate data.
 * Run:  npx tsx prisma/seed-real-profiles.ts
 */
import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

async function main() {
  // ── 1. WIPE ──────────────────────────────────────────────────────────────
  await prisma.swipe.deleteMany();
  await prisma.booking.deleteMany();
  await prisma.service.deleteMany();
  await prisma.serviceProvider.deleteMany();
  await prisma.pet.deleteMany();

  console.log("✓ Cleared all previous data");

  // ── 2. PETS ───────────────────────────────────────────────────────────────
  // Coords for Cairo neighbourhoods
  const coords: Record<string, { lat: number; lng: number }> = {
    maadi:          { lat: 29.9608, lng: 31.2567 },
    zamalek:        { lat: 30.0599, lng: 31.2195 },
    newcairo:       { lat: 30.0300, lng: 31.4700 },
    nasrcity:       { lat: 30.0593, lng: 31.3340 },
    mohandiseen:    { lat: 30.0587, lng: 31.1982 },
    heliopolis:     { lat: 30.0896, lng: 31.3195 },
    dokki:          { lat: 30.0376, lng: 31.2117 },
    shubra:         { lat: 30.1108, lng: 31.2425 },
    katameya:       { lat: 29.9820, lng: 31.4900 },
    october:        { lat: 29.9360, lng: 30.9080 },
  };

  const pets = [
    // ── PHOTO-BASED PROFILES (dog-1 through dog-15) ────────────────────────
    {
      id: "p-luna",
      name: "Luna",
      photoUrl: "/dogs/dog-1.jpg",
      species: "dog",
      breed: "Border Collie Mix",
      ageMonths: 3,
      gender: "Female",
      size: "small",
      energyLevel: "high",
      goodWithKids: true,
      goodWithPets: true,
      description: "One of two puppies from the same litter — chocolate brown with a white chest. Found in Maadi with her sibling Oreo. Both are healthy, dewormed, and ready for their forever homes.",
      shelterName: "Maadi Rescue Network",
      shelterEmail: "rescue@maadi-paws.eg",
      location: "Maadi, Cairo",
      latitude: coords.maadi.lat,
      longitude: coords.maadi.lng,
    },
    {
      id: "p-max",
      name: "Max",
      photoUrl: "/dogs/dog-2.jpg",
      species: "dog",
      breed: "Border Collie Mix",
      ageMonths: 26,
      gender: "Male",
      size: "medium",
      energyLevel: "high",
      goodWithKids: true,
      goodWithPets: true,
      description: "Chocolate brown and white Border Collie mix, comfortable in a modern apartment setting. Friendly, sociable, and loves being around people and other dogs.",
      shelterName: "Zamalek Pet Friends",
      shelterEmail: "info@zamalekoets.eg",
      location: "Zamalek, Cairo",
      latitude: coords.zamalek.lat,
      longitude: coords.zamalek.lng,
    },
    {
      id: "p-coco",
      name: "Coco",
      photoUrl: "/dogs/dog-3.jpg",
      species: "dog",
      breed: "Border Collie Mix",
      ageMonths: 18,
      gender: "Female",
      size: "medium",
      energyLevel: "medium",
      goodWithKids: true,
      goodWithPets: true,
      description: "Brown and white beauty who loves lounging in the garden and strolling through outdoor cafés. Coco is calm, well-mannered, and turns heads wherever she goes.",
      shelterName: "New Cairo Paws",
      shelterEmail: "adopt@newcairopaws.eg",
      location: "New Cairo, Cairo",
      latitude: coords.newcairo.lat,
      longitude: coords.newcairo.lng,
    },
    {
      id: "p-rio",
      name: "Rio",
      photoUrl: "/dogs/dog-4.jpg",
      species: "dog",
      breed: "Border Collie Mix",
      ageMonths: 24,
      gender: "Male",
      size: "medium",
      energyLevel: "high",
      goodWithKids: true,
      goodWithPets: true,
      description: "Adventurous and photogenic brown/white Border Collie mix spotted across Cairo in multiple settings — compounds, parks, indoors. Rio adapts to anything and loves every minute of it.",
      shelterName: "Maadi Rescue Network",
      shelterEmail: "rescue@maadi-paws.eg",
      location: "Maadi, Cairo",
      latitude: coords.maadi.lat,
      longitude: coords.maadi.lng,
    },
    {
      id: "p-zara",
      name: "Zara",
      photoUrl: "/dogs/dog-5.jpg",
      species: "dog",
      breed: "Border Collie Mix",
      ageMonths: 12,
      gender: "Female",
      size: "medium",
      energyLevel: "high",
      goodWithKids: true,
      goodWithPets: true,
      description: "Zara loves running by the lake in her compound with her furry best friend. Athletic, playful, and full of personality — she needs a home with space and an active owner.",
      shelterName: "New Cairo Paws",
      shelterEmail: "adopt@newcairopaws.eg",
      location: "Katameya Heights, New Cairo",
      latitude: coords.katameya.lat,
      longitude: coords.katameya.lng,
    },
    {
      id: "p-toby",
      name: "Toby",
      photoUrl: "/dogs/dog-6.jpg",
      species: "dog",
      breed: "Border Collie Mix",
      ageMonths: 14,
      gender: "Male",
      size: "medium",
      energyLevel: "medium",
      goodWithKids: true,
      goodWithPets: true,
      description: "Fluffy brown and white dog with a gorgeous bushy tail, happy to play on grass with other dogs. Toby is easygoing, gentle, and loves outdoor hangouts in Heliopolis.",
      shelterName: "Heliopolis Animal Care",
      shelterEmail: "care@heliopolis-pets.eg",
      location: "Heliopolis, Cairo",
      latitude: coords.heliopolis.lat,
      longitude: coords.heliopolis.lng,
    },
    {
      id: "p-nala",
      name: "Nala",
      photoUrl: "/dogs/dog-7.jpg",
      species: "dog",
      breed: "Papillon Mix",
      ageMonths: 36,
      gender: "Female",
      size: "small",
      energyLevel: "low",
      goodWithKids: true,
      goodWithPets: false,
      description: "Tiny brown and white Papillon mix who claims the most comfortable spots in the house — currently the orange bean bag. Nala is a lap dog through and through, perfect for apartment life.",
      shelterName: "Mohandiseen Pet Rescue",
      shelterEmail: "rescue@mohandeseen-pets.eg",
      location: "Mohandiseen, Giza",
      latitude: coords.mohandiseen.lat,
      longitude: coords.mohandiseen.lng,
    },
    {
      id: "p-pearl",
      name: "Pearl",
      photoUrl: "/dogs/dog-8.jpg",
      species: "dog",
      breed: "Bichon Frisé Mix",
      ageMonths: 48,
      gender: "Female",
      size: "small",
      energyLevel: "low",
      goodWithKids: true,
      goodWithPets: true,
      description: "This little white scruffy adventurer loves paddling at the beach. Pearl is calm, friendly, well-groomed, and completely content wherever her humans are.",
      shelterName: "Nasr City Strays",
      shelterEmail: "adopt@nasrcity-pets.eg",
      location: "Nasr City, Cairo",
      latitude: coords.nasrcity.lat,
      longitude: coords.nasrcity.lng,
    },
    {
      id: "p-shadow",
      name: "Shadow",
      photoUrl: "/dogs/dog-9.jpg",
      species: "dog",
      breed: "White Mixed Breed",
      ageMonths: 30,
      gender: "Male",
      size: "medium",
      energyLevel: "medium",
      goodWithKids: true,
      goodWithPets: true,
      description: "Elegant white dog who loves golden-hour walks in Zamalek gardens with his brown companion. Shadow is calm, dependable, and loves quiet evening strolls.",
      shelterName: "Zamalek Pet Friends",
      shelterEmail: "info@zamalekoets.eg",
      location: "Zamalek, Cairo",
      latitude: coords.zamalek.lat,
      longitude: coords.zamalek.lng,
    },
    {
      id: "p-biscuit",
      name: "Biscuit",
      photoUrl: "/dogs/dog-10.jpg",
      species: "dog",
      breed: "White Mixed Breed",
      ageMonths: 24,
      gender: "Male",
      size: "medium",
      energyLevel: "medium",
      goodWithKids: true,
      goodWithPets: true,
      description: "Curious and investigative, Biscuit always has his nose to the ground. Spotted in Heliopolis exploring grassy patches. He is playful, social, and bonds easily with other dogs.",
      shelterName: "Heliopolis Animal Care",
      shelterEmail: "care@heliopolis-pets.eg",
      location: "Heliopolis, Cairo",
      latitude: coords.heliopolis.lat,
      longitude: coords.heliopolis.lng,
    },
    {
      id: "p-mocha",
      name: "Mocha",
      photoUrl: "/dogs/dog-11.jpg",
      species: "dog",
      breed: "Border Collie Mix",
      ageMonths: 4,
      gender: "Male",
      size: "small",
      energyLevel: "high",
      goodWithKids: true,
      goodWithPets: true,
      description: "Look at that face. Mocha is a chocolate brown puppy with the most expressive smile you've ever seen. He is 4 months old, fully vaccinated, and will absolutely steal your heart.",
      shelterName: "Maadi Rescue Network",
      shelterEmail: "rescue@maadi-paws.eg",
      location: "Maadi, Cairo",
      latitude: coords.maadi.lat,
      longitude: coords.maadi.lng,
    },
    {
      id: "p-teddy",
      name: "Teddy",
      photoUrl: "/dogs/dog-12.jpg",
      species: "dog",
      breed: "Mixed Breed Puppy",
      ageMonths: 2,
      gender: "Male",
      size: "small",
      energyLevel: "low",
      goodWithKids: true,
      goodWithPets: true,
      description: "Dressed in his tiny red sweater and lounging on a Persian rug like a little prince, Teddy is the ultimate indoor companion. He is 2 months old and ready to be spoiled rotten.",
      shelterName: "New Cairo Paws",
      shelterEmail: "adopt@newcairopaws.eg",
      location: "New Cairo, Cairo",
      latitude: coords.newcairo.lat,
      longitude: coords.newcairo.lng,
    },
    {
      id: "p-brownie",
      name: "Brownie",
      photoUrl: "/dogs/dog-13.jpg",
      species: "dog",
      breed: "Border Collie Mix",
      ageMonths: 3,
      gender: "Female",
      size: "small",
      energyLevel: "high",
      goodWithKids: true,
      goodWithPets: true,
      description: "Fluffy chocolate brown puppy caught mid-crunch at her food bowl in the garden. Brownie is a healthy, round little pup who eats well and plays hard. Needs a garden home!",
      shelterName: "New Cairo Paws",
      shelterEmail: "adopt@newcairopaws.eg",
      location: "Katameya Heights, New Cairo",
      latitude: coords.katameya.lat,
      longitude: coords.katameya.lng,
    },
    {
      id: "p-surf",
      name: "Surf",
      photoUrl: "/dogs/dog-14.jpg",
      species: "dog",
      breed: "Border Collie Mix",
      ageMonths: 18,
      gender: "Male",
      size: "medium",
      energyLevel: "high",
      goodWithKids: true,
      goodWithPets: true,
      description: "Surf is the dog who shows up to the pool party and makes it 10x better. This brown/white Border Collie mix is adventurous, water-curious, and always ready for the next adventure.",
      shelterName: "Zamalek Pet Friends",
      shelterEmail: "info@zamalekoets.eg",
      location: "Zamalek, Cairo",
      latitude: coords.zamalek.lat,
      longitude: coords.zamalek.lng,
    },
    {
      id: "p-storm",
      name: "Storm",
      photoUrl: "/dogs/dog-15.jpg",
      species: "dog",
      breed: "Border Collie Mix",
      ageMonths: 20,
      gender: "Female",
      size: "small",
      energyLevel: "medium",
      goodWithKids: true,
      goodWithPets: true,
      description: "Storm rocks her black raincoat on late-night garden walks like a canine runway model. This compact brown/white girl is calm, confident, and surprisingly stylish.",
      shelterName: "Mohandiseen Pet Rescue",
      shelterEmail: "rescue@mohandeseen-pets.eg",
      location: "Mohandiseen, Giza",
      latitude: coords.mohandiseen.lat,
      longitude: coords.mohandiseen.lng,
    },

    // ── EXTRA DIVERSE PROFILES (to stress-test matching & filters) ──────────
    {
      id: "p-caramel",
      name: "Caramel",
      photoUrl: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=600&h=800&fit=crop",
      species: "dog",
      breed: "Golden Retriever",
      ageMonths: 60,
      gender: "Female",
      size: "large",
      energyLevel: "medium",
      goodWithKids: true,
      goodWithPets: true,
      description: "Classic golden girl with the softest fur and the gentlest soul. Caramel is 5 years old, fully trained, and ready for a family that deserves her unconditional love.",
      shelterName: "Maadi Rescue Network",
      shelterEmail: "rescue@maadi-paws.eg",
      location: "Maadi, Cairo",
      latitude: coords.maadi.lat,
      longitude: coords.maadi.lng,
    },
    {
      id: "p-zeus",
      name: "Zeus",
      photoUrl: "https://images.unsplash.com/photo-1568572933382-74d440642117?w=600&h=800&fit=crop",
      species: "dog",
      breed: "German Shepherd",
      ageMonths: 36,
      gender: "Male",
      size: "large",
      energyLevel: "high",
      goodWithKids: false,
      goodWithPets: false,
      description: "Loyal, intelligent, and highly trainable German Shepherd seeking an experienced owner with space to run. Zeus is perfectly behaved one-on-one but needs a patient handler.",
      shelterName: "Heliopolis Animal Care",
      shelterEmail: "care@heliopolis-pets.eg",
      location: "Heliopolis, Cairo",
      latitude: coords.heliopolis.lat,
      longitude: coords.heliopolis.lng,
    },
    {
      id: "p-bambi",
      name: "Bambi",
      photoUrl: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=800&fit=crop",
      species: "dog",
      breed: "Labrador Retriever",
      ageMonths: 8,
      gender: "Female",
      size: "large",
      energyLevel: "high",
      goodWithKids: true,
      goodWithPets: true,
      description: "Yellow Lab with limitless enthusiasm and zero personal space boundaries — she will sit on your lap. Bambi is 8 months old, house-trained, and genuinely the happiest dog alive.",
      shelterName: "New Cairo Paws",
      shelterEmail: "adopt@newcairopaws.eg",
      location: "New Cairo, Cairo",
      latitude: coords.newcairo.lat,
      longitude: coords.newcairo.lng,
    },
    {
      id: "p-oscar",
      name: "Oscar",
      photoUrl: "https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=600&h=800&fit=crop",
      species: "dog",
      breed: "Dachshund",
      ageMonths: 84,
      gender: "Male",
      size: "small",
      energyLevel: "low",
      goodWithKids: true,
      goodWithPets: false,
      description: "Seven-year-old Dachshund with strong opinions about couch spots and nap schedules. Oscar is a senior gentleman looking for a calm home where his wisdom is respected.",
      shelterName: "Zamalek Pet Friends",
      shelterEmail: "info@zamalekoets.eg",
      location: "Zamalek, Cairo",
      latitude: coords.zamalek.lat,
      longitude: coords.zamalek.lng,
    },
    {
      id: "p-daisy",
      name: "Daisy",
      photoUrl: "https://images.unsplash.com/photo-1583511655826-05700d52f4d9?w=600&h=800&fit=crop",
      species: "dog",
      breed: "Pomeranian",
      ageMonths: 14,
      gender: "Female",
      size: "small",
      energyLevel: "high",
      goodWithKids: true,
      goodWithPets: true,
      description: "Fluffy cream Pomeranian who treats every room like a runway and every person like a fan. Daisy is 14 months, fully vaccinated, and sparkles in Mohandiseen.",
      shelterName: "Mohandiseen Pet Rescue",
      shelterEmail: "rescue@mohandeseen-pets.eg",
      location: "Mohandiseen, Giza",
      latitude: coords.mohandiseen.lat,
      longitude: coords.mohandiseen.lng,
    },
    {
      id: "p-atlas",
      name: "Atlas",
      photoUrl: "https://images.unsplash.com/photo-1605568427561-40dd23c2acea?w=600&h=800&fit=crop",
      species: "dog",
      breed: "Siberian Husky",
      ageMonths: 48,
      gender: "Male",
      size: "large",
      energyLevel: "high",
      goodWithKids: true,
      goodWithPets: true,
      description: "Grey and white Husky who was born for adventure but currently lives in New Cairo and makes it work. Atlas needs 2+ hours of exercise daily and repays you with howling renditions of your favourite songs.",
      shelterName: "New Cairo Paws",
      shelterEmail: "adopt@newcairopaws.eg",
      location: "New Cairo, Cairo",
      latitude: coords.newcairo.lat,
      longitude: coords.newcairo.lng,
    },
    {
      id: "p-penny",
      name: "Penny",
      photoUrl: "https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?w=600&h=800&fit=crop",
      species: "dog",
      breed: "Beagle",
      ageMonths: 72,
      gender: "Female",
      size: "medium",
      energyLevel: "medium",
      goodWithKids: true,
      goodWithPets: true,
      description: "Tricolor Beagle with a nose that could crack a cold case and a tail that never stops wagging. Penny is 6 years old, healthy, and looking for a patient family in Dokki.",
      shelterName: "Nasr City Strays",
      shelterEmail: "adopt@nasrcity-pets.eg",
      location: "Dokki, Giza",
      latitude: coords.dokki.lat,
      longitude: coords.dokki.lng,
    },
    {
      id: "p-lola",
      name: "Lola",
      photoUrl: "https://images.unsplash.com/photo-1558788353-f76d92427f16?w=600&h=800&fit=crop",
      species: "dog",
      breed: "Maltese",
      ageMonths: 24,
      gender: "Female",
      size: "small",
      energyLevel: "low",
      goodWithKids: true,
      goodWithPets: true,
      description: "Snow-white Maltese who has mastered the art of looking perpetually groomed and effortlessly cute. Lola is 2 years old, loves lap time, and thrives in apartment life.",
      shelterName: "Zamalek Pet Friends",
      shelterEmail: "info@zamalekoets.eg",
      location: "Zamalek, Cairo",
      latitude: coords.zamalek.lat,
      longitude: coords.zamalek.lng,
    },
    {
      id: "p-rex",
      name: "Rex",
      photoUrl: "https://images.unsplash.com/photo-1601979031925-424e53b6caaa?w=600&h=800&fit=crop",
      species: "dog",
      breed: "Rottweiler Mix",
      ageMonths: 36,
      gender: "Male",
      size: "large",
      energyLevel: "medium",
      goodWithKids: false,
      goodWithPets: false,
      description: "Don't let the serious face fool you — Rex is a big softy once he knows you. This 3-year-old Rottweiler mix needs an experienced owner and a home with a garden in Shubra.",
      shelterName: "Heliopolis Animal Care",
      shelterEmail: "care@heliopolis-pets.eg",
      location: "Shubra, Cairo",
      latitude: coords.shubra.lat,
      longitude: coords.shubra.lng,
    },
    {
      id: "p-choco",
      name: "Choco",
      photoUrl: "https://images.unsplash.com/photo-1596492784531-6e6eb5ea9993?w=600&h=800&fit=crop",
      species: "dog",
      breed: "Chocolate Labrador",
      ageMonths: 28,
      gender: "Male",
      size: "large",
      energyLevel: "high",
      goodWithKids: true,
      goodWithPets: true,
      description: "Dark chocolate Lab with the energy of a puppy and the appetite of a grown man. Choco is 2.5 years old, super affectionate, and needs a home that won't mind muddy paw prints.",
      shelterName: "Nasr City Strays",
      shelterEmail: "adopt@nasrcity-pets.eg",
      location: "Nasr City, Cairo",
      latitude: coords.nasrcity.lat,
      longitude: coords.nasrcity.lng,
    },
  ];

  for (const pet of pets) {
    await prisma.pet.upsert({
      where: { id: pet.id },
      update: pet,
      create: pet,
    });
  }
  console.log(`✓ Seeded ${pets.length} pets`);

  // ── 3. SERVICE PROVIDERS ──────────────────────────────────────────────────
  const providers = [
    // MAADI
    {
      id: "sp-omar-maadi",
      name: "Omar Ashraf — Dog Walker",
      bio: "Professional dog walker serving Maadi and Degla since 2019. Solo and group walks. Insured.",
      avatarEmoji: "🦮",
      location: "Maadi, Cairo",
      neighborhood: "Maadi",
      latitude: 29.9608, longitude: 31.2567,
      rating: 4.9, reviewCount: 87, isVerified: true,
      whatsapp: "+201001234567",
    },
    {
      id: "sp-laila-maadi",
      name: "Laila Hassan — Pet Sitter",
      bio: "Home-based sitter in Maadi with a garden. Max 2 dogs at a time. Vet on speed-dial.",
      avatarEmoji: "🏡",
      location: "Maadi, Cairo",
      neighborhood: "Maadi",
      latitude: 29.9590, longitude: 31.2555,
      rating: 4.8, reviewCount: 64, isVerified: true,
      whatsapp: "+201009876543",
    },
    // ZAMALEK / DOWNTOWN
    {
      id: "sp-dr-nour-zamalek",
      name: "Dr. Nour Mostafa — Vet Clinic",
      bio: "Veterinarian with 12 years experience. Zamalek clinic + home visits across Cairo.",
      avatarEmoji: "🩺",
      location: "Zamalek, Cairo",
      neighborhood: "Zamalek",
      latitude: 30.0599, longitude: 31.2195,
      rating: 4.9, reviewCount: 230, isVerified: true,
      whatsapp: "+201112223344",
    },
    // NEW CAIRO
    {
      id: "sp-pawfect-newcairo",
      name: "Pawfect Grooming Studio",
      bio: "Premium dog grooming salon in New Cairo. Luxury baths, breed-specific cuts, pet spa treatments.",
      avatarEmoji: "✂️",
      location: "New Cairo, Cairo",
      neighborhood: "New Cairo",
      latitude: 30.0300, longitude: 31.4700,
      rating: 4.8, reviewCount: 143, isVerified: true,
      whatsapp: "+201234567890",
    },
    {
      id: "sp-cairo-pet-hotel",
      name: "Cairo Pet Resort & Hotel",
      bio: "5-star boarding in New Cairo with CCTV, outdoor play areas, daily reports, and vet on call.",
      avatarEmoji: "🏨",
      location: "New Cairo, Cairo",
      neighborhood: "New Cairo",
      latitude: 30.0350, longitude: 31.4800,
      rating: 4.7, reviewCount: 199, isVerified: true,
      whatsapp: "+201555666777",
    },
    // NASR CITY
    {
      id: "sp-swift-taxi",
      name: "Swift Pet Taxi",
      bio: "AC-equipped pet transport across Cairo and Giza. Vet visits, airport, and emergency runs.",
      avatarEmoji: "🚗",
      location: "Nasr City, Cairo",
      neighborhood: "Nasr City",
      latitude: 30.0593, longitude: 31.3340,
      rating: 4.7, reviewCount: 112, isVerified: true,
      whatsapp: "+201667788990",
    },
    // MOHANDISEEN
    {
      id: "sp-dr-sara-emergency",
      name: "Dr. Sara Khalil — Emergency Vet",
      bio: "24/7 emergency vet serving Mohandiseen, Dokki, and 6th October. Home visits available at night.",
      avatarEmoji: "🚨",
      location: "Mohandiseen, Giza",
      neighborhood: "Mohandiseen",
      latitude: 30.0587, longitude: 31.1982,
      rating: 4.95, reviewCount: 178, isVerified: true,
      whatsapp: "+201788990011",
    },
    {
      id: "sp-green-paws-mohan",
      name: "Green Paws Salon — Mohandiseen",
      bio: "Walk-in grooming salon in Mohandiseen. Affordable baths, nail trims, and breed cuts. No appointment needed.",
      avatarEmoji: "🌿",
      location: "Mohandiseen, Giza",
      neighborhood: "Mohandiseen",
      latitude: 30.0570, longitude: 31.2010,
      rating: 4.6, reviewCount: 95, isVerified: false,
      whatsapp: "+201234512345",
    },
    // HELIOPOLIS
    {
      id: "sp-hana-heliopolis",
      name: "Hana Nabil — Pet Sitter & Trainer",
      bio: "Certified trainer and sitter in Heliopolis. Specialises in anxious and rescue dogs. Home garden available.",
      avatarEmoji: "🎓",
      location: "Heliopolis, Cairo",
      neighborhood: "Heliopolis",
      latitude: 30.0896, longitude: 31.3195,
      rating: 4.9, reviewCount: 58, isVerified: true,
      whatsapp: "+201345678901",
    },
    // 6TH OCTOBER
    {
      id: "sp-paws-october",
      name: "Paws & Play — 6th October",
      bio: "Daycare, grooming, and boarding in 6th October. Large outdoor play area and group socialization sessions.",
      avatarEmoji: "🐾",
      location: "6th October, Giza",
      neighborhood: "6th October",
      latitude: 29.9360, longitude: 30.9080,
      rating: 4.6, reviewCount: 74, isVerified: true,
      whatsapp: "+201456789012",
    },
    // DOKKI
    {
      id: "sp-dr-walid-dokki",
      name: "Dr. Walid Saad — Vet & Surgery",
      bio: "Full-service veterinary clinic in Dokki. General medicine, surgery, dentistry, and X-ray on-site.",
      avatarEmoji: "🏥",
      location: "Dokki, Giza",
      neighborhood: "Dokki",
      latitude: 30.0376, longitude: 31.2117,
      rating: 4.8, reviewCount: 167, isVerified: true,
      whatsapp: "+201567890123",
    },
    // KATAMEYA / NEW CAIRO COMPOUNDS
    {
      id: "sp-mike-compound",
      name: "Mike Ramzy — Compound Dog Walker",
      bio: "Specialist in compound walking circuits — Katameya, Palm Hills, Stone Park. Daily and weekly packages.",
      avatarEmoji: "🏃",
      location: "Katameya, New Cairo",
      neighborhood: "New Cairo",
      latitude: 29.9820, longitude: 31.4900,
      rating: 4.8, reviewCount: 51, isVerified: true,
      whatsapp: "+201678901234",
    },
  ];

  for (const p of providers) {
    await prisma.serviceProvider.upsert({
      where: { id: p.id },
      update: p,
      create: p,
    });
  }
  console.log(`✓ Seeded ${providers.length} service providers`);

  // ── 4. SERVICES ───────────────────────────────────────────────────────────
  const services = [
    // ── WALKING ──
    { id: "svc-walk-30-maadi",     providerId: "sp-omar-maadi",     category: "walks",     title: "30-Min Solo Walk — Maadi",       description: "30-minute solo neighbourhood walk with GPS tracking and post-walk report.",          priceEGP: 150, durationMins: 30,  atHomeOnly: false, segment: "B" },
    { id: "svc-walk-60-maadi",     providerId: "sp-omar-maadi",     category: "walks",     title: "60-Min Solo Walk — Maadi",       description: "Extended 60-minute walk through Maadi's garden streets.",                            priceEGP: 250, durationMins: 60,  atHomeOnly: false, segment: "B" },
    { id: "svc-walk-group-maadi",  providerId: "sp-omar-maadi",     category: "walks",     title: "Group Walk (3–5 dogs)",          description: "Socialisation group walk for calm dogs. Max 5 dogs per session.",                    priceEGP: 100, durationMins: 45,  atHomeOnly: false, segment: "B" },
    { id: "svc-walk-30-compound",  providerId: "sp-mike-compound",  category: "walks",     title: "30-Min Compound Walk",           description: "Morning or evening walk inside your compound (Katameya, Stone Park, Palm Hills).",    priceEGP: 175, durationMins: 30,  atHomeOnly: false, segment: "A" },
    { id: "svc-walk-60-compound",  providerId: "sp-mike-compound",  category: "walks",     title: "60-Min Compound Walk",           description: "Full circuit walk with enrichment activities. GPS report included.",                  priceEGP: 300, durationMins: 60,  atHomeOnly: false, segment: "A" },
    { id: "svc-walk-weekly",       providerId: "sp-mike-compound",  category: "walks",     title: "Weekly Walk Package (5 walks)",  description: "5 x 45-min walks per week. Saves 15% vs individual bookings.",                       priceEGP: 750, durationMins: 45,  atHomeOnly: false, segment: "A" },

    // ── SITTING ──
    { id: "svc-sit-overnight",     providerId: "sp-laila-maadi",    category: "sitting",   title: "Overnight Home Sit — Maadi",     description: "Sitter stays at your home overnight. Includes 2 walks and feeding. Maadi/Degla only.", priceEGP: 500, durationMins: 720, atHomeOnly: true,  segment: "B" },
    { id: "svc-sit-daycare",       providerId: "sp-laila-maadi",    category: "sitting",   title: "Full-Day Daycare at Sitter Home", description: "Drop your dog at Laila's garden home (8am–8pm). Meals, walks, and play included.",  priceEGP: 350, durationMins: 720, atHomeOnly: false, segment: "B" },
    { id: "svc-sit-homevisit",     providerId: "sp-laila-maadi",    category: "sitting",   title: "30-Min Home Visit",              description: "Check-in visit: feeding, bathroom break, playtime. Perfect for busy days.",          priceEGP: 180, durationMins: 30,  atHomeOnly: true,  segment: "B" },
    { id: "svc-sit-heliopolis",    providerId: "sp-hana-heliopolis", category: "sitting",  title: "Expert Sit + Training — Heliopolis", description: "Hana sits your dog AND works on basic commands / anxiety management.",          priceEGP: 450, durationMins: 480, atHomeOnly: false, segment: "A" },
    { id: "svc-daycare-october",   providerId: "sp-paws-october",   category: "sitting",   title: "Full-Day Daycare — 6th October", description: "Group play and socialisation at Paws & Play. Large outdoor yard, socialisation sessions.", priceEGP: 280, durationMins: 600, atHomeOnly: false, segment: "B" },

    // ── VETS ──
    { id: "svc-vet-checkup",       providerId: "sp-dr-nour-zamalek", category: "vets",     title: "General Checkup — Clinic",       description: "Full physical exam, parasite check, weight, and health record update.",             priceEGP: 400, durationMins: 30,  atHomeOnly: false, segment: "A" },
    { id: "svc-vet-vaccine",       providerId: "sp-dr-nour-zamalek", category: "vets",     title: "Annual Vaccination",             description: "Core vaccines (DHLPP or FVRCP). Includes certificate and sticker for passport.",    priceEGP: 350, durationMins: 20,  atHomeOnly: false, segment: "A" },
    { id: "svc-vet-dental",        providerId: "sp-dr-nour-zamalek", category: "vets",     title: "Dental Cleaning (under sedation)", description: "Full dental scale and polish under light sedation. Pre-anesthesia bloodwork included.", priceEGP: 1200, durationMins: 90, atHomeOnly: false, segment: "A" },
    { id: "svc-vet-telehealth",    providerId: "sp-dr-nour-zamalek", category: "vets",     title: "Video Consult — WhatsApp",       description: "15-min video consultation for non-emergencies, medication advice, and follow-ups.",  priceEGP: 200, durationMins: 15,  atHomeOnly: false, segment: "A" },
    { id: "svc-vet-homevisit",     providerId: "sp-dr-nour-zamalek", category: "vets",     title: "Home Visit — All Cairo",         description: "Dr. Nour comes to you. Includes exam, medication, and report. 1–2hr notice.",       priceEGP: 700, durationMins: 45,  atHomeOnly: true,  segment: "A" },
    { id: "svc-vet-dokki-checkup", providerId: "sp-dr-walid-dokki",  category: "vets",     title: "General Checkup — Dokki Clinic", description: "Comprehensive exam at Dr. Walid's full-service Dokki clinic.",                     priceEGP: 350, durationMins: 30,  atHomeOnly: false, segment: "B" },
    { id: "svc-vet-dokki-dental",  providerId: "sp-dr-walid-dokki",  category: "vets",     title: "Dental Cleaning — Dokki",        description: "Dental cleaning + X-ray if needed. Full in-house lab and surgery suite.",           priceEGP: 1000, durationMins: 90, atHomeOnly: false, segment: "B" },
    { id: "svc-vet-dokki-surgery", providerId: "sp-dr-walid-dokki",  category: "vets",     title: "Spay / Neuter — Dokki",          description: "Routine spay or neuter with pre-op bloodwork, anaesthesia, and post-op kit.",       priceEGP: 2000, durationMins: 120, atHomeOnly: false, segment: "B" },
    { id: "svc-vet-telehealth-2",  providerId: "sp-dr-walid-dokki",  category: "vets",     title: "Phone / WhatsApp Consult",       description: "Quick phone consult with Dr. Walid for minor concerns and prescription refills.",   priceEGP: 150, durationMins: 10,  atHomeOnly: false, segment: "B" },

    // ── GROOMING ──
    { id: "svc-groom-bath-s",      providerId: "sp-pawfect-newcairo", category: "grooming", title: "Bath & Blow Dry — Small Dog",    description: "Shampoo, condition, blow dry, and ear clean for small breeds (under 10 kg).",      priceEGP: 200, durationMins: 60,  atHomeOnly: false, segment: "A" },
    { id: "svc-groom-bath-l",      providerId: "sp-pawfect-newcairo", category: "grooming", title: "Bath & Blow Dry — Large Dog",    description: "Same premium bath for large breeds (10 kg+). Golden Retrievers, Huskies, etc.",    priceEGP: 350, durationMins: 90,  atHomeOnly: false, segment: "A" },
    { id: "svc-groom-full",        providerId: "sp-pawfect-newcairo", category: "grooming", title: "Full Groom — Breed Cut",         description: "Bath + full body breed-specific scissor cut + nails + ear cleaning + bandana.",    priceEGP: 500, durationMins: 120, atHomeOnly: false, segment: "A" },
    { id: "svc-groom-nails",       providerId: "sp-pawfect-newcairo", category: "grooming", title: "Nail Trim & File",               description: "Quick nail clip and file. No appointment needed. Walk-ins welcome.",                priceEGP: 100, durationMins: 15,  atHomeOnly: false, segment: "A" },
    { id: "svc-groom-spa",         providerId: "sp-pawfect-newcairo", category: "grooming", title: "Luxury Spa Package",             description: "Full groom + deep conditioning mask + paw balm + cologne + photos for your pet's IG.", priceEGP: 750, durationMins: 150, atHomeOnly: false, segment: "A" },
    { id: "svc-groom-mohan-bath",  providerId: "sp-green-paws-mohan", category: "grooming", title: "Bath & Dry — Mohandiseen",       description: "No-frills quality bath and blow dry. Walk-in accepted. Any breed.",                 priceEGP: 180, durationMins: 60,  atHomeOnly: false, segment: "B" },
    { id: "svc-groom-mohan-full",  providerId: "sp-green-paws-mohan", category: "grooming", title: "Full Groom — Mohandiseen",       description: "Bath + haircut + nails + ears at Green Paws. Value pricing, consistent quality.",  priceEGP: 350, durationMins: 90,  atHomeOnly: false, segment: "B" },
    { id: "svc-groom-mohan-nails", providerId: "sp-green-paws-mohan", category: "grooming", title: "Nail Trim — Mohandiseen",        description: "Quick walk-in nail clip. No booking needed.",                                       priceEGP: 80,  durationMins: 15,  atHomeOnly: false, segment: "B" },
    { id: "svc-groom-october",     providerId: "sp-paws-october",    category: "grooming",  title: "Groom & Play — 6th October",    description: "Drop-in groom + daycare. Your dog is groomed then plays for the day.",             priceEGP: 450, durationMins: 180, atHomeOnly: false, segment: "B" },

    // ── HOTEL ──
    { id: "svc-hotel-overnight",   providerId: "sp-cairo-pet-hotel",  category: "hotel",    title: "Overnight Boarding — Private Suite", description: "Your dog gets a private suite with a bed, toys, and 3 walks. CCTV access for owners.", priceEGP: 750, durationMins: 1440, atHomeOnly: false, segment: "A" },
    { id: "svc-hotel-weekly",      providerId: "sp-cairo-pet-hotel",  category: "hotel",    title: "Weekly Boarding Package",        description: "7 nights in a private suite. Includes daily grooming brush, vet check-in, and daily photos.", priceEGP: 4500, durationMins: 10080, atHomeOnly: false, segment: "A" },
    { id: "svc-hotel-daycare",     providerId: "sp-cairo-pet-hotel",  category: "hotel",    title: "Full-Day Daycare at Resort",     description: "8am–8pm at the resort with group play, socialisation, and 2 walks. Pick-up/drop-off add-on available.", priceEGP: 350, durationMins: 720, atHomeOnly: false, segment: "A" },
    { id: "svc-hotel-october",     providerId: "sp-paws-october",     category: "hotel",    title: "Overnight Boarding — 6th October", description: "Overnight in a shared or private room with outdoor access. Affordable option outside central Cairo.", priceEGP: 500, durationMins: 1440, atHomeOnly: false, segment: "B" },

    // ── TAXI ──
    { id: "svc-taxi-vet",          providerId: "sp-swift-taxi",       category: "taxi",     title: "Vet Run — Any Cairo Clinic",     description: "AC car with pet-safe carrier for vet appointments. Driver waits. Door-to-door.",  priceEGP: 250, durationMins: 60,  atHomeOnly: false, segment: "B" },
    { id: "svc-taxi-airport",      providerId: "sp-swift-taxi",       category: "taxi",     title: "Airport Pet Transport",          description: "Safe transport to/from Cairo International for pet cargo or owner travel. 1-hr notice.", priceEGP: 500, durationMins: 90,  atHomeOnly: false, segment: "B" },
    { id: "svc-taxi-emergency",    providerId: "sp-swift-taxi",       category: "taxi",     title: "Emergency Vet Taxi — 24/7",      description: "Any time, any emergency. Fastest available car to the nearest 24/7 vet clinic.", priceEGP: 650, durationMins: 30,  atHomeOnly: false, segment: "B" },

    // ── EMERGENCY ──
    { id: "svc-emergency-home",    providerId: "sp-dr-sara-emergency", category: "emergency", title: "Emergency Home Visit — 24/7",  description: "Dr. Sara comes to you, any hour. Stabilisation, pain meds, and triage assessment included.", priceEGP: 900, durationMins: 60, atHomeOnly: true, segment: "A" },
    { id: "svc-emergency-consult", providerId: "sp-dr-sara-emergency", category: "emergency", title: "Emergency WhatsApp Triage",    description: "Immediate video/photo triage on WhatsApp. Dr. Sara assesses severity and advises next steps.", priceEGP: 200, durationMins: 15, atHomeOnly: false, segment: "B" },
    { id: "svc-emergency-heliopolis", providerId: "sp-hana-heliopolis", category: "emergency", title: "After-Hours Pet Check-In",   description: "Hana accepts drop-off emergencies at her Heliopolis home when clinics are closed.", priceEGP: 400, durationMins: 60, atHomeOnly: false, segment: "A" },
  ];

  for (const s of services) {
    await prisma.service.upsert({
      where: { id: s.id },
      update: { ...s, species: "all", isAvailable: true },
      create: { ...s, species: "all", isAvailable: true },
    });
  }
  console.log(`✓ Seeded ${services.length} services`);
  console.log(`\n🐾 Done! ${pets.length} pets · ${providers.length} providers · ${services.length} services`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
