import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const pets = [
  {
    name: "Max", species: "dog", breed: "Golden Retriever", ageMonths: 24,
    gender: "male", size: "large", energyLevel: "high",
    goodWithKids: true, goodWithPets: true,
    description: "Max is a sunshine-yellow ball of joy who loves fetch, swimming, and cuddles in equal measure. He passed his Canine Good Citizen test and never met a stranger.",
    photoUrl: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=600&fit=crop",
    shelterName: "Happy Paws Rescue", shelterEmail: "adopt@happypaws.org",
    location: "Austin, TX", latitude: 30.2672, longitude: -97.7431,
  },
  {
    name: "Luna", species: "cat", breed: "Domestic Shorthair", ageMonths: 14,
    gender: "female", size: "small", energyLevel: "medium",
    goodWithKids: true, goodWithPets: false,
    description: "Luna is a silver-grey charmer who loves window perches and chasing laser pointers. She prefers to be the only pet but adores her humans completely.",
    photoUrl: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400&h=600&fit=crop",
    shelterName: "City Cat Shelter", shelterEmail: "cats@cityshelter.org",
    location: "Portland, OR", latitude: 45.5231, longitude: -122.6765,
  },
  {
    name: "Buddy", species: "dog", breed: "Labrador Retriever", ageMonths: 48,
    gender: "male", size: "large", energyLevel: "medium",
    goodWithKids: true, goodWithPets: true,
    description: "Buddy is the calmest Labrador you'll ever meet. At four years old, he's past his wild puppy days and now just wants a couch, a family, and a daily walk.",
    photoUrl: "https://images.unsplash.com/photo-1561948955-570b270e7c36?w=400&h=600&fit=crop",
    shelterName: "Second Chances Rescue", shelterEmail: "hello@secondchances.org",
    location: "Denver, CO", latitude: 39.7392, longitude: -104.9903,
  },
  {
    name: "Mochi", species: "cat", breed: "Ragdoll", ageMonths: 7,
    gender: "female", size: "medium", energyLevel: "low",
    goodWithKids: true, goodWithPets: true,
    description: "Mochi goes limp in your arms the moment you pick her up — true to her Ragdoll nature. She purrs at full volume and has never scratched anything she wasn't supposed to.",
    photoUrl: "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=600&fit=crop",
    shelterName: "Fluffy Friends", shelterEmail: "adopt@fluffyfriends.net",
    location: "Seattle, WA", latitude: 47.6062, longitude: -122.3321,
  },
  {
    name: "Rocky", species: "dog", breed: "French Bulldog", ageMonths: 28,
    gender: "male", size: "small", energyLevel: "low",
    goodWithKids: true, goodWithPets: true,
    description: "Rocky snores, sploots, and demands belly rubs every fifteen minutes. His idea of exercise is a slow stroll to the nearest patch of grass. Perfect apartment dog.",
    photoUrl: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=400&h=600&fit=crop",
    shelterName: "Happy Paws Rescue", shelterEmail: "adopt@happypaws.org",
    location: "Austin, TX", latitude: 30.2672, longitude: -97.7431,
  },
  {
    name: "Shadow", species: "cat", breed: "Bombay", ageMonths: 60,
    gender: "male", size: "medium", energyLevel: "low",
    goodWithKids: false, goodWithPets: false,
    description: "Shadow is a sleek black panther who rules his domain with quiet dignity. He will choose you — not the other way around. But when he does, you'll have a loyal companion for life.",
    photoUrl: "https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=400&h=600&fit=crop",
    shelterName: "City Cat Shelter", shelterEmail: "cats@cityshelter.org",
    location: "Portland, OR", latitude: 45.5231, longitude: -122.6765,
  },
  {
    name: "Daisy", species: "dog", breed: "Beagle", ageMonths: 18,
    gender: "female", size: "medium", energyLevel: "high",
    goodWithKids: true, goodWithPets: true,
    description: "Daisy's nose leads the way on every walk. She's a classic Beagle — curious, food-motivated, and always singing. She needs a securely fenced yard and a patient family.",
    photoUrl: "https://images.unsplash.com/photo-1586671267731-da2cf3ceeb80?w=400&h=600&fit=crop",
    shelterName: "Second Chances Rescue", shelterEmail: "hello@secondchances.org",
    location: "Denver, CO", latitude: 39.7392, longitude: -104.9903,
  },
  {
    name: "Oliver", species: "cat", breed: "Maine Coon", ageMonths: 30,
    gender: "male", size: "large", energyLevel: "medium",
    goodWithKids: true, goodWithPets: true,
    description: "Oliver is a dog-like cat — he follows you from room to room, greets you at the door, and has been known to play fetch. His tufted ears and lion mane make him impossible to ignore.",
    photoUrl: "https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=400&h=600&fit=crop",
    shelterName: "Fluffy Friends", shelterEmail: "adopt@fluffyfriends.net",
    location: "Seattle, WA", latitude: 47.6062, longitude: -122.3321,
  },
  {
    name: "Bella", species: "dog", breed: "Poodle Mix", ageMonths: 84,
    gender: "female", size: "small", energyLevel: "low",
    goodWithKids: false, goodWithPets: true,
    description: "Bella is a senior sweetheart who just wants a warm lap and a quiet home. She's hypoallergenic, house-trained, and fully potty trained. Perfect for a retired or calm household.",
    photoUrl: "https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?w=400&h=600&fit=crop",
    shelterName: "Senior Paws Foundation", shelterEmail: "love@seniorpaws.org",
    location: "Miami, FL", latitude: 25.7617, longitude: -80.1918,
  },
  {
    name: "Charlie", species: "dog", breed: "Border Collie", ageMonths: 36,
    gender: "male", size: "medium", energyLevel: "high",
    goodWithKids: true, goodWithPets: false,
    description: "Charlie will herd your children, master every trick you teach him, and still have energy left over. He needs a job — agility, flyball, or farm work. Not for apartment life.",
    photoUrl: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=400&h=600&fit=crop",
    shelterName: "Working Dog Rescue", shelterEmail: "border@workingdogs.org",
    location: "Bozeman, MT", latitude: 45.6770, longitude: -111.0429,
  },
  {
    name: "Cleo", species: "cat", breed: "Abyssinian", ageMonths: 22,
    gender: "female", size: "small", energyLevel: "high",
    goodWithKids: true, goodWithPets: true,
    description: "Cleo thinks she's royalty and she's right. She'll leap to every high surface in your home, demand treats on schedule, and sleep on your keyboard precisely when you need it.",
    photoUrl: "https://images.unsplash.com/photo-1561948955-570b270e7c36?w=400&h=600&fit=crop",
    shelterName: "City Cat Shelter", shelterEmail: "cats@cityshelter.org",
    location: "Portland, OR", latitude: 45.5231, longitude: -122.6765,
  },
  {
    name: "Bear", species: "dog", breed: "Bernese Mountain Dog", ageMonths: 16,
    gender: "male", size: "large", energyLevel: "medium",
    goodWithKids: true, goodWithPets: true,
    description: "Bear is a gentle giant who thinks he's a lap dog. He loves snow, children, and long hikes. His tri-colour coat is show-stopping and his temperament is as calm as mountain air.",
    photoUrl: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=600&fit=crop&seed=2",
    shelterName: "Mountain Pet Rescue", shelterEmail: "adopt@mountainrescue.org",
    location: "Salt Lake City, UT", latitude: 40.7608, longitude: -111.8910,
  },
  // ── Real local rescue dogs ─────────────────────────────────────────────────
  {
    name: "Cooper", species: "dog", breed: "Mixed Breed", ageMonths: 20,
    gender: "male", size: "medium", energyLevel: "high",
    goodWithKids: true, goodWithPets: true,
    description: "Cooper is a playful mixed-breed rescue with the biggest smile you'll ever see. He loves people, other dogs, and anyone willing to throw a ball. A true adventure companion.",
    photoUrl: "/dogs/dog-1.jpg",
    shelterName: "Local Rescue", shelterEmail: "rescue@localrescue.org",
    location: "New York, NY", latitude: 40.7128, longitude: -74.0060,
  },
  {
    name: "Duke", species: "dog", breed: "Mixed Breed", ageMonths: 36,
    gender: "male", size: "large", energyLevel: "medium",
    goodWithKids: true, goodWithPets: false,
    description: "Duke is a big, soulful boy who loves long walks and slow mornings. He's gentle with children but prefers to be the only dog in his kingdom. A loyal companion through and through.",
    photoUrl: "/dogs/dog-2.jpg",
    shelterName: "Local Rescue", shelterEmail: "rescue@localrescue.org",
    location: "New York, NY", latitude: 40.7128, longitude: -74.0060,
  },
  {
    name: "Rosie", species: "dog", breed: "Mixed Breed", ageMonths: 12,
    gender: "female", size: "small", energyLevel: "high",
    goodWithKids: true, goodWithPets: true,
    description: "Rosie is a tiny tornado of joy. She's young, fast, and endlessly entertaining. She loves squeaky toys, belly rubs, and running laps around the living room at full speed.",
    photoUrl: "/dogs/dog-3.jpg",
    shelterName: "Local Rescue", shelterEmail: "rescue@localrescue.org",
    location: "New York, NY", latitude: 40.7128, longitude: -74.0060,
  },
  {
    name: "Zeus", species: "dog", breed: "Mixed Breed", ageMonths: 48,
    gender: "male", size: "large", energyLevel: "low",
    goodWithKids: true, goodWithPets: true,
    description: "Zeus may have a powerful name but he's the gentlest soul you'll meet. He's past the hyper stage and now specialises in couch naps and neighbourhood strolls.",
    photoUrl: "/dogs/dog-4.jpg",
    shelterName: "Local Rescue", shelterEmail: "rescue@localrescue.org",
    location: "Los Angeles, CA", latitude: 34.0522, longitude: -118.2437,
  },
  {
    name: "Peanut", species: "dog", breed: "Mixed Breed", ageMonths: 9,
    gender: "female", size: "small", energyLevel: "high",
    goodWithKids: true, goodWithPets: true,
    description: "Peanut is the smallest dog with the biggest personality. She bounces off the walls, learns tricks in minutes, and somehow always ends up in your lap despite not technically fitting.",
    photoUrl: "/dogs/dog-5.jpg",
    shelterName: "Local Rescue", shelterEmail: "rescue@localrescue.org",
    location: "Los Angeles, CA", latitude: 34.0522, longitude: -118.2437,
  },
  {
    name: "Bruno", species: "dog", breed: "Mixed Breed", ageMonths: 30,
    gender: "male", size: "medium", energyLevel: "medium",
    goodWithKids: true, goodWithPets: true,
    description: "Bruno is that dog everyone loves immediately. Calm, friendly, and social — he's great at the dog park and even better on the couch. Trained, vaccinated, and ready to go home.",
    photoUrl: "/dogs/dog-6.jpg",
    shelterName: "Local Rescue", shelterEmail: "rescue@localrescue.org",
    location: "Chicago, IL", latitude: 41.8781, longitude: -87.6298,
  },
  {
    name: "Nala", species: "dog", breed: "Mixed Breed", ageMonths: 18,
    gender: "female", size: "medium", energyLevel: "medium",
    goodWithKids: false, goodWithPets: true,
    description: "Nala is a quiet, observant girl who warms up slowly but loves deeply. She does best in a calm adult home with another mellow dog for company. Once she trusts you, she's yours forever.",
    photoUrl: "/dogs/dog-7.jpg",
    shelterName: "Local Rescue", shelterEmail: "rescue@localrescue.org",
    location: "Chicago, IL", latitude: 41.8781, longitude: -87.6298,
  },
  {
    name: "Koda", species: "dog", breed: "Mixed Breed", ageMonths: 15,
    gender: "male", size: "medium", energyLevel: "high",
    goodWithKids: true, goodWithPets: true,
    description: "Koda is the ultimate outdoor adventure buddy. Hiking trails, beach runs, fetch in the park — he's up for anything. He'll push you to be more active and thank you with endless affection.",
    photoUrl: "/dogs/dog-8.jpg",
    shelterName: "Local Rescue", shelterEmail: "rescue@localrescue.org",
    location: "Phoenix, AZ", latitude: 33.4484, longitude: -112.0740,
  },
  {
    name: "Ginger", species: "dog", breed: "Mixed Breed", ageMonths: 60,
    gender: "female", size: "small", energyLevel: "low",
    goodWithKids: false, goodWithPets: true,
    description: "Ginger is a wise senior lady who's lived a full life and now just wants a warm bed and a peaceful home. She's quiet, house-trained, and the perfect companion for a calm lifestyle.",
    photoUrl: "/dogs/dog-9.jpg",
    shelterName: "Senior Paws Foundation", shelterEmail: "love@seniorpaws.org",
    location: "Phoenix, AZ", latitude: 33.4484, longitude: -112.0740,
  },
  {
    name: "Archie", species: "dog", breed: "Mixed Breed", ageMonths: 24,
    gender: "male", size: "medium", energyLevel: "medium",
    goodWithKids: true, goodWithPets: false,
    description: "Archie is a charming, curious boy who loves exploring new places. He's smart, eager to please, and responds beautifully to positive training. Best as the only pet so he gets all your love.",
    photoUrl: "/dogs/dog-10.jpg",
    shelterName: "Local Rescue", shelterEmail: "rescue@localrescue.org",
    location: "Houston, TX", latitude: 29.7604, longitude: -95.3698,
  },
  {
    name: "Bella-Rose", species: "dog", breed: "Mixed Breed", ageMonths: 10,
    gender: "female", size: "small", energyLevel: "high",
    goodWithKids: true, goodWithPets: true,
    description: "Bella-Rose is pure sunshine in puppy form. She loves everyone she meets, plays well with dogs of all sizes, and is currently learning her basic commands. A blank canvas of potential.",
    photoUrl: "/dogs/dog-11.jpg",
    shelterName: "Local Rescue", shelterEmail: "rescue@localrescue.org",
    location: "Houston, TX", latitude: 29.7604, longitude: -95.3698,
  },
  {
    name: "Tank", species: "dog", breed: "Mixed Breed", ageMonths: 42,
    gender: "male", size: "large", energyLevel: "low",
    goodWithKids: true, goodWithPets: true,
    description: "Despite the tough name, Tank is an absolute marshmallow. He's big, soft, and completely unaware of his size. Loves children, other dogs, and sleeping in sunbeams.",
    photoUrl: "/dogs/dog-12.jpg",
    shelterName: "Second Chances Rescue", shelterEmail: "hello@secondchances.org",
    location: "Philadelphia, PA", latitude: 39.9526, longitude: -75.1652,
  },
  {
    name: "Hazel", species: "dog", breed: "Mixed Breed", ageMonths: 14,
    gender: "female", size: "medium", energyLevel: "medium",
    goodWithKids: true, goodWithPets: true,
    description: "Hazel is sweet, gentle, and always happy to see you. She's got expressive eyes that will absolutely make you feel guilty for going to work. House-trained, leash-trained, and dog-park approved.",
    photoUrl: "/dogs/dog-13.jpg",
    shelterName: "Happy Paws Rescue", shelterEmail: "adopt@happypaws.org",
    location: "Philadelphia, PA", latitude: 39.9526, longitude: -75.1652,
  },
  {
    name: "Scout", species: "dog", breed: "Mixed Breed", ageMonths: 8,
    gender: "male", size: "medium", energyLevel: "high",
    goodWithKids: true, goodWithPets: true,
    description: "Scout lives up to his name — always exploring, always curious, always finding the one thing in the yard he wasn't supposed to dig up. Young and full of potential for the right active family.",
    photoUrl: "/dogs/dog-14.jpg",
    shelterName: "Working Dog Rescue", shelterEmail: "border@workingdogs.org",
    location: "San Antonio, TX", latitude: 29.4241, longitude: -98.4936,
  },
  {
    name: "Maple", species: "dog", breed: "Mixed Breed", ageMonths: 32,
    gender: "female", size: "medium", energyLevel: "medium",
    goodWithKids: true, goodWithPets: true,
    description: "Maple is the kind of dog that makes you wonder how nobody adopted her already. She's calm, affectionate, walks beautifully on a leash, and is great with everyone she meets.",
    photoUrl: "/dogs/dog-15.jpg",
    shelterName: "Happy Paws Rescue", shelterEmail: "adopt@happypaws.org",
    location: "San Antonio, TX", latitude: 29.4241, longitude: -98.4936,
  },
];

async function main() {
  console.log("Seeding Petinder database...");
  for (const pet of pets) {
    await prisma.pet.upsert({
      where: { id: pet.name.toLowerCase() + "-seed" },
      update: { latitude: pet.latitude, longitude: pet.longitude },
      create: { id: pet.name.toLowerCase() + "-seed", ...pet },
    });
  }
  console.log(`Seeded ${pets.length} pets.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
