import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const pets = [
  {
    name: "Max",
    species: "dog",
    breed: "Golden Retriever",
    ageMonths: 24,
    gender: "male",
    size: "large",
    energyLevel: "high",
    goodWithKids: true,
    goodWithPets: true,
    description: "Max is a sunshine-yellow ball of joy who loves fetch, swimming, and cuddles in equal measure. He passed his Canine Good Citizen test and never met a stranger.",
    photoUrl: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=600&fit=crop",
    shelterName: "Happy Paws Rescue",
    shelterEmail: "adopt@happypaws.org",
    location: "Austin, TX",
  },
  {
    name: "Luna",
    species: "cat",
    breed: "Domestic Shorthair",
    ageMonths: 14,
    gender: "female",
    size: "small",
    energyLevel: "medium",
    goodWithKids: true,
    goodWithPets: false,
    description: "Luna is a silver-grey charmer who loves window perches and chasing laser pointers. She prefers to be the only pet but adores her humans completely.",
    photoUrl: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400&h=600&fit=crop",
    shelterName: "City Cat Shelter",
    shelterEmail: "cats@cityshelter.org",
    location: "Portland, OR",
  },
  {
    name: "Buddy",
    species: "dog",
    breed: "Labrador Retriever",
    ageMonths: 48,
    gender: "male",
    size: "large",
    energyLevel: "medium",
    goodWithKids: true,
    goodWithPets: true,
    description: "Buddy is the calmest Labrador you'll ever meet. At four years old, he's past his wild puppy days and now just wants a couch, a family, and a daily walk.",
    photoUrl: "https://images.unsplash.com/photo-1561948955-570b270e7c36?w=400&h=600&fit=crop",
    shelterName: "Second Chances Rescue",
    shelterEmail: "hello@secondchances.org",
    location: "Denver, CO",
  },
  {
    name: "Mochi",
    species: "cat",
    breed: "Ragdoll",
    ageMonths: 7,
    gender: "female",
    size: "medium",
    energyLevel: "low",
    goodWithKids: true,
    goodWithPets: true,
    description: "Mochi goes limp in your arms the moment you pick her up — true to her Ragdoll nature. She purrs at full volume and has never scratched anything she wasn't supposed to.",
    photoUrl: "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=600&fit=crop",
    shelterName: "Fluffy Friends",
    shelterEmail: "adopt@fluffyfriends.net",
    location: "Seattle, WA",
  },
  {
    name: "Rocky",
    species: "dog",
    breed: "French Bulldog",
    ageMonths: 28,
    gender: "male",
    size: "small",
    energyLevel: "low",
    goodWithKids: true,
    goodWithPets: true,
    description: "Rocky snores, sploots, and demands belly rubs every fifteen minutes. His idea of exercise is a slow stroll to the nearest patch of grass. Perfect apartment dog.",
    photoUrl: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=400&h=600&fit=crop",
    shelterName: "Happy Paws Rescue",
    shelterEmail: "adopt@happypaws.org",
    location: "Austin, TX",
  },
  {
    name: "Shadow",
    species: "cat",
    breed: "Bombay",
    ageMonths: 60,
    gender: "male",
    size: "medium",
    energyLevel: "low",
    goodWithKids: false,
    goodWithPets: false,
    description: "Shadow is a sleek black panther who rules his domain with quiet dignity. He will choose you — not the other way around. But when he does, you'll have a loyal companion for life.",
    photoUrl: "https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=400&h=600&fit=crop",
    shelterName: "City Cat Shelter",
    shelterEmail: "cats@cityshelter.org",
    location: "Portland, OR",
  },
  {
    name: "Daisy",
    species: "dog",
    breed: "Beagle",
    ageMonths: 18,
    gender: "female",
    size: "medium",
    energyLevel: "high",
    goodWithKids: true,
    goodWithPets: true,
    description: "Daisy's nose leads the way on every walk. She's a classic Beagle — curious, food-motivated, and always singing. She needs a securely fenced yard and a patient family.",
    photoUrl: "https://images.unsplash.com/photo-1586671267731-da2cf3ceeb80?w=400&h=600&fit=crop",
    shelterName: "Second Chances Rescue",
    shelterEmail: "hello@secondchances.org",
    location: "Denver, CO",
  },
  {
    name: "Oliver",
    species: "cat",
    breed: "Maine Coon",
    ageMonths: 30,
    gender: "male",
    size: "large",
    energyLevel: "medium",
    goodWithKids: true,
    goodWithPets: true,
    description: "Oliver is a dog-like cat — he follows you from room to room, greets you at the door, and has been known to play fetch. His tufted ears and lion mane make him impossible to ignore.",
    photoUrl: "https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=400&h=600&fit=crop",
    shelterName: "Fluffy Friends",
    shelterEmail: "adopt@fluffyfriends.net",
    location: "Seattle, WA",
  },
  {
    name: "Bella",
    species: "dog",
    breed: "Poodle Mix",
    ageMonths: 84,
    gender: "female",
    size: "small",
    energyLevel: "low",
    goodWithKids: false,
    goodWithPets: true,
    description: "Bella is a senior sweetheart who just wants a warm lap and a quiet home. She's hypoallergenic, house-trained, and fully potty trained. Perfect for a retired or calm household.",
    photoUrl: "https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?w=400&h=600&fit=crop",
    shelterName: "Senior Paws Foundation",
    shelterEmail: "love@seniorpaws.org",
    location: "Miami, FL",
  },
  {
    name: "Charlie",
    species: "dog",
    breed: "Border Collie",
    ageMonths: 36,
    gender: "male",
    size: "medium",
    energyLevel: "high",
    goodWithKids: true,
    goodWithPets: false,
    description: "Charlie will herd your children, master every trick you teach him, and still have energy left over. He needs a job — agility, flyball, or farm work. Not for apartment life.",
    photoUrl: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=400&h=600&fit=crop",
    shelterName: "Working Dog Rescue",
    shelterEmail: "border@workingdogs.org",
    location: "Bozeman, MT",
  },
  {
    name: "Cleo",
    species: "cat",
    breed: "Abyssinian",
    ageMonths: 22,
    gender: "female",
    size: "small",
    energyLevel: "high",
    goodWithKids: true,
    goodWithPets: true,
    description: "Cleo thinks she's royalty and she's right. She'll leap to every high surface in your home, demand treats on schedule, and sleep on your keyboard precisely when you need it.",
    photoUrl: "https://images.unsplash.com/photo-1561948955-570b270e7c36?w=400&h=600&fit=crop",
    shelterName: "City Cat Shelter",
    shelterEmail: "cats@cityshelter.org",
    location: "Portland, OR",
  },
  {
    name: "Bear",
    species: "dog",
    breed: "Bernese Mountain Dog",
    ageMonths: 16,
    gender: "male",
    size: "large",
    energyLevel: "medium",
    goodWithKids: true,
    goodWithPets: true,
    description: "Bear is a gentle giant who thinks he's a lap dog. He loves snow, children, and long hikes. His tri-colour coat is show-stopping and his temperament is as calm as mountain air.",
    photoUrl: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=600&fit=crop&seed=2",
    shelterName: "Mountain Pet Rescue",
    shelterEmail: "adopt@mountainrescue.org",
    location: "Salt Lake City, UT",
  },
];

async function main() {
  console.log("Seeding Petinder database...");
  for (const pet of pets) {
    await prisma.pet.upsert({
      where: { id: pet.name.toLowerCase() + "-seed" },
      update: {},
      create: { id: pet.name.toLowerCase() + "-seed", ...pet },
    });
  }
  console.log(`Seeded ${pets.length} pets.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
